const lessons = [
  { text: 'I can type.', completed: false, time: null, missed: null},
  { text: 'Wisdom begins in wonder.', completed: false, time: null, missed: null},
  { text: 'Wise men talk because they have something to say; fools because they have to say something.', completed: false, time: null, missed: null},
  { text: 'Dig the well before you are thirsty.', completed: false, time: null, missed: null},
  { text: 'A man with no enemies is a man with no character.', completed: false, time: null, missed: null},
  { text: 'Going to church doesn’t make you a Christian any more than standing in your garage makes you a car.', completed: false, time: null, missed: null},
  { text: 'All that is necessary for the triumph of evil is that good men do nothing.', completed: false, time: null, missed: null},
  { text: 'You may choose to look the other way but you can never again say that you did not know.', completed: false, time: null, missed: null},
  { text: 'I had rather be right than be president.', completed: false, time: null, missed: null},
  { text: 'Basic research is what I am doing when I don’t know what I am doing.', completed: false, time: null, missed: null},
  { text: 'If you want something that you’ve never had, you must be willing to do something you’ve never done.', completed: false, time: null, missed: null},
  { text: 'Worry is a cycle of inefficient thoughts whirling around a center of fear.', completed: false, time: null, missed: null},
  { text: 'It is better to die for the truth than to live for a lie.', completed: false, time: null, missed: null},
  { text: 'The key to prayer is not changing God’s mind, The key to prayer is changing yours.', completed: false, time: null, missed: null},
  { text: 'Never hate people who are jealous of you, the think that you’re better than them.', completed: false, time: null, missed: null},
  { text: 'Dream as if you’ll live forever. Live as if you’ll die tomorrow.', completed: false, time: null, missed: null},
  { text: 'To achieve great things, two things are needed; a plan, and not quite enough time.', completed: false, time: null, missed: null},
  { text: 'Never forget that everything Hitler did in Germany was legal.', completed: false, time: null, missed: null},
  { text: 'The world is a dangerous place to live; not because of the people who are evil, but because of the people who don’t do anything about it.', completed: false, time: null, missed: null},
  { text: 'Reading is more listening than talking. It is appreciation, rather than creation. It is discovery, rather than fabrication.', completed: false, time: null, missed: null},
  { text: 'Even if you fall on your face you’re still moving forward.', completed: false, time: null, missed: null},
  { text: 'Education begins in delight and ends in a clarification of life.', completed: false, time: null, missed: null},
  { text: 'Don’t tax me, don’t tax thee, tax that fellow behind the tree.', completed: false, time: null, missed: null},
  { text: 'My own eyes are not enough for me, I will see through those of others.', completed: false, time: null, missed: null},
  { text: 'Courage is fear that has said its prayers.', completed: false, time: null, missed: null},
  { text: 'Love is friendship caught on fire.', completed: false, time: null, missed: null},
  { text: 'If war is ever lawful then peace is sometimes sinful.', completed: false, time: null, missed: null},
  { text: 'A story without wickedness is a wicked story.', completed: false, time: null, missed: null},
  { text: 'Injustice anywhere is a threat to justice everywhere.', completed: false, time: null, missed: null},
  { text: 'Foresight is what you will see; hindsight, what you have seen. Insight is the ability to use both and understand what you see.', completed: false, time: null, missed: null},
]

export default lessons
